---
- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Check if is WSL
      set_fact: is_wsl="{{ true if 'Microsoft' in ansible_kernel else false }}"

    - include: update_os.yml

    - name: Install prerequisites
      package:
        name: "{{ item }}"
      with_items:
        - git
        - python-pip

  roles:
    - ansible
    - vagrant
    - golang
    - terraform
    - docker
    - sublimetext
    - { role: chrome, when: not is_wsl }
    - { role: virtualbox, when: not is_wsl }
    - { role: franz, when: not is_wsl }
    - { role: spotify, when: not is_wsl }

  tasks:
    - name: Install utils
      package:
        name: "{{ item }}"
      with_items:
       - tmux
       - vim
       - zsh
       - jq

    - name: Install utils from pip
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - awscli

    - name: Install GUI utils
      package:
        name: "{{ item }}"
      with_items:
        - terminator
        - pidgin
        - pidgin-sipe
      when: not is_wsl

- hosts: localhost
  connection: local
  tasks:
    - name: Set username
      set_fact: username={{ ansible_env.USER }}

    - include: user.yml

    - include: wsl.yml
      when: is_wsl
      static: no
