---
- hosts: localhost
  connection: local
  tasks:
    - name: Give passwordless access to {{ ansible_user }}
      become: yes
      copy:
        dest: /etc/sudoers.d/{{ ansible_user }}
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"

    - name: Tap custom repositories
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - caskroom/drivers
        - wata727/tflint

    - name: Install utils
      homebrew:
        name: "{{ item }}"
      with_items:
        - ansible
        - clang-format
        - docker-compose
        - ffmpeg
        - gnu-sed
        - gnu-tar
        - htop
        - kubernetes-helm
        - npm
        - packer
        - pv
        - rbenv
        - terraform
        - tflint
        - tmux
        - wget
        - xz
        - zsh

    - name: Install apps
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        - displaylink
        - docker
        - franz
        - google-chrome
        - hipchat
        - iterm2
        - minikube
        - skype
        - skype-for-business
        - slack
        - slate
        - spotify
        - subler
        - sublime-text
        - transmission
        - vagrant
        - virtualbox
        - visual-studio-code
        - vlc
        - xquartz

    - name: Install tools from pip
      become: yes
      pip:
        executable: /usr/local/bin/pip
        name: "{{ item }}"
      with_items:
        - ansible-lint
        - docker-py
        - yamllint
