---
- hosts: localhost
  connection: local
  tasks:
    - name: Give passwordless access to {{ ansible_user }}
      become: yes
      copy:
        dest: /etc/sudoers.d/{{ ansible_user }}
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"

    - name: Tap custom repositories
      homebrew_tap:
        name: "{{ item }}"
      with_items:
        - caskroom/drivers
        - wata727/tflint

    - name: Install utils
      homebrew:
        name: "{{ item }}"
      with_items:
        - ansible
        - ansible-lint
        - awscli
        - clang-format
        - docker-compose
        - ffmpeg
        - gnu-sed
        - gnu-tar
        - gnupg
        - go
        - htop
        - jmeter
        - jq
        - kubernetes-cli
        - kubernetes-helm
        - mariadb
        - npm
        - packer
        - pv
        - rbenv
        - terraform
        - terraform-docs
        - tflint
        - tmux
        - wget
        - xz
        - zsh

    - name: Install apps
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        # Drivers
        - bose-updater
        - displaylink
        - jabra-suite
        # Development
        - chefdk
        - docker
        - google-cloud-sdk
        - iterm2
        - minikube
        - sublime-text
        - vagrant
        - virtualbox
        - visual-studio-code
        # Messaging
        - franz
        - skype
        - skype-for-business
        - slack
        # Media
        - calibre
        - spotify
        - subler
        - transmission
        - vlc
        # Desktop
        - google-chrome
        - onedrive
        - slate
        - xquartz
        # Network
        - charles
        - wireshark

    - name: Install tools from pip
      become: yes
      pip:
        executable: /usr/local/bin/pip
        name: "{{ item }}"
      with_items:
        - docker-py
        - yamllint

    - name: Install dark theme for slack
      blockinfile:
        path: /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          document.addEventListener('DOMContentLoaded', function() {
            $.ajax({
              url: 'https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css',
              success: function(css) {
                $("<style></style>").appendTo('head').html(css);
              }
            });
          });
