#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  connection: local
  tasks:
    - include: sudoers.yml

    - name: Install utils
      homebrew:
        name: "{{ item }}"
      with_items:
        - ansible
        - ansible-lint
        - awscli
        - clang-format
        - docker-compose
        - dos2unix
        - ffmpeg
        - gnu-sed
        - gnu-tar
        - gnupg
        - go
        - htop
        - jq
        - kubectx
        - kubernetes-cli
        - kubernetes-helm
        - nmap
        - node
        - npm
        - pv
        - rbenv
        - shellcheck
        - shfmt
        - terraform
        - terraform-docs
        - tmux
        - wata727/tflint/tflint
        - watch
        - wget
        - xz
        - yamllint
        - zsh

    - name: Install apps
      homebrew_cask:
        name: "{{ item }}"
      with_items:
        # Desktop
        - google-chrome
        - onedrive
        - slate
        - xquartz
        # Messaging
        - rambox
        - skype
        - skype-for-business
        - slack
        # Development
        # - chefdk
        - iterm2
        - sublime-text
        - visual-studio-code
        - docker
        - virtualbox
        - vagrant
        - google-cloud-sdk
        # Media
        - calibre
        - spotify
        - subler
        - transmission
        - vlc
        # Network
        - wireshark

    - name: Install dark theme for slack
      blockinfile:
        path: /Applications/Slack.app/Contents/Resources/app.asar.unpacked/src/static/ssb-interop.js
        marker: "// {mark} ANSIBLE MANAGED BLOCK"
        block: |
          document.addEventListener('DOMContentLoaded', function() {
            $.ajax({
              url: 'https://cdn.rawgit.com/laCour/slack-night-mode/master/css/raw/black.css',
              success: function(css) {
                $("<style></style>").appendTo('head').html(css);
              }
            });
          });
