---
- name: Find latest version
  uri:
    url: https://api.github.com/repos/meetfranz/franz/tags
    return_content: yes
  register: franz_version

- name: Set franz_version
  set_fact:
    franz_version: "{{ franz_version.json[0].name[1:] }}"

- name: Install franz
  apt:
    deb: "{{ franz_pkg_url }}"
