---
- name: Install Sublime Text repository key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg

- name: Install Sublime Text repository
  apt_repository:
    repo: "deb https://download.sublimetext.com/ apt/stable/"

- name: Install Sublime Text
  apt:
    name: sublime-text
    update_cache: yes
