---
- name: Install negativo17 repository key
  rpm_key:
    key: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

- name: Install negativo17 repository
  yum_repository:
    name: negativo17
    description: negativo17 spotify client
    baseurl: https://negativo17.org/repos/spotify/fedora-{{ ansible_distribution_version }}/x86_64/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: yes

- name: Install Spotify
  dnf:
    name: spotify-client
