---
- name: Install chrome repository key
  rpm_key:
    key: "{{ chrome_repository_key_url }}"

- name: "Install chrome repository"
  yum_repository:
    name: chrome
    description: Google Chrome
    baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: "{{ chrome_repository_key_url }}"
    gpgcheck: yes

- name: "Install chrome"
  dnf:
    name: "{{ chrome_package }}"
