---
- name: Add VirtualBox repository key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc

- name: Install VirtualBox repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"

- name: Install VirtualBox
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - dkms
    - virtualbox-5.1
