---
- name: Remove old docker packages
  apt: name={{ item }} state=absent
  with_items:
    - docker.io
    - docker-engine

- name: Install CA certificates
  apt: name={{ item }}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - linux-image-extra-virtual
    - linux-image-extra-{{ ansible_kernel }}

- name: Install docker repository Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Install docker
  apt: name={{ item }}
  with_items:
    - docker-ce
    - python-docker
